
version: "3"
services:

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: sharif-proxy
    restart: always
    ports:
      - 1080:1080
    expose:
      - 1080

  loadbalancer:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
